[CREATE] 상세페이지 요리,재료 조회 로직 구현 완료
wecode-bootcamp-korea/21-1st-Ojusmarket-backend pull request #10
Opened 2021-06-13 04:09 UTC by kevin-hyun

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 상세페이지 자료 조회 로직 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- ingredient의 상세페이지 자료를 조회하는 로직을 구현했습니다( id , name , storage, image_url , related) 
- related는 ingredient가 쓰이게 되는 recipe의 정보입니다 ( id, name, image_url) 
- recipe의 상세페이지 자료를 조회하는 로직을 구현했습니다( id , name , storage, image_url , related) 
- related는 recipe를 만들 때 필요한 ingredient의 정보입니다 ( id, name, image_url)
- 기존에 객체를 조회하고 거기서 다시 filter를 적용하는 과정을 거치는 로직으로 작성을 했지만 django의 double underscore로 M:M관계의 자료를 더 쉽게 가져올 수 있다는 것을 공부하고 난 후 로직에 적용을 했습니다.
- 루프문을 돌릴 때 for 문을 사용하여 list에 append를 사용하는 로직 대신 list comprehension을 사용하여 속도를 12ms만큼 향상 시켰습니다( 40ms --> 28ms) 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 현재 깃이 충돌할까봐 ingredient,recipe의 subpage를 ingredient 폴더에서 작업하고 있고 ingredient,recipe의 mainpage를 recipe페이지에서 작업을 하고 있습니다. 조금 기형적으로 구성이 되고 있는 것 같습니다.
- 폴더를 다시 구성을 해서 기능적으로 (mainpage, subpage폴더로 구성을 할지 ) 구분을 할지 
- 기존 방식으로 (ingredient, recipe 폴더에)하되 각각 폴더에 메인페이지 조회와 상세페이지 조회를 합쳐넣을지(ingredient 폴더 안에 ingredient mainpage, subpage 조회 로직 같이 위치)  고민입니다.
- ingredient url = ingredient/detail  //  recipe url = recipe/detail로 구성했는데 restful한지 궁금합니다.
- 에러처리를 exception으로 통합한다음에 print(e)로 에러메시지를 확인하는 방식으로 진행했는데 에러를 세분화하는 것이 좋은지 아니면 백엔드에서만 에러의 원인을 파악하는 것이 좋은 지 궁금합니다. 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-13 04:16 UTC, kevin-hyun commented
포스트맨 통신 결과 첨부합니다~~ 

<img width="856" alt="Screen Shot 2021-06-13 at 13 06 57" src="https://user-images.githubusercontent.com/78840341/121795209-7e629180-cc49-11eb-9a4d-d9e6539b9c76.png">
<img width="856" alt="Screen Shot 2021-06-13 at 13 07 42" src="https://user-images.githubusercontent.com/78840341/121795210-83274580-cc49-11eb-8d9d-84859728816b.png">

2021-06-14 05:56 UTC, lordmyshepherd requested changes

2021-06-14 05:56 UTC, lordmyshepherd commented on ingredient/urls.py
> +    path('/detail',ShowIngredientInfo.as_view()),
`Ingredient`와 `Recipe`를 분리해주세요!
여기서, URI를 `detail`이라고 만드신 것은 detail page 정보를 불러오는 것처럼 느껴집니다.
(PR도 상세페이지라고 적으신 것을 보니 그렇습니다!)

API는 페이지에 의존적으로 만들어지지 않도록 주의해야 합니다. 데이터 기준으로 만들려고 고민하셔야 합니다!
recipe와 ingredient 정보는 상품 상세페이지에서 뿐만 아니라 여러 곳에서 호출해서 사용할 수 있어야합니다.

`http://127.0.0.1:8000/ingrdient/1`, `http://127.0.0.1:8000/recipe/1` 이런식으로요.

> REST API 설계 규칙을 잘 고민해보시면 도움이 될 것 같습니다!
> 자원(데이터) 하나를 불러올 때는, query parameter가 아니라 path parameter를 사용해서 구현해주셔야 합니다. (REST 설계 규칙)

2021-06-14 05:56 UTC, lordmyshepherd commented on ingredient/views.py
> +from django.views      import View
한칸 띄워주세요!

2021-06-14 05:56 UTC, lordmyshepherd commented on ingredient/views.py
> +class ShowIngredientInfo(View):
class 명은 명사로 만들어주세요! Info를 붙이는 것도 너무 verbose한 것 같습니다!

```suggestion
class Ingredient(View):
```

2021-06-14 05:56 UTC, lordmyshepherd commented on ingredient/views.py
> +            request_id  = request.GET.get('id',None)
위에서 말씀드린대로 자원 하나를 받아올 때는 path paramter를 사용해서 구현해주세요.
```suggestion

```

2021-06-14 05:56 UTC, lordmyshepherd commented on ingredient/views.py
> +            print(e)
프린트문 지워주세요.

2021-06-14 05:56 UTC, lordmyshepherd commented on ingredient/views.py
> +            }
해당 재료를 가져올 때, 관련된 recipe도 가져오는 형태인가요? 
아래와 같은 형태로 가져와야 더 명확할 것 같아요!

```python
Ingredient = {
    "id" : 1,
    "name" : "고구마",
    "price" : "...",
    "related_recipe" : [
        {
            "id" : 10,
            "name" : "고구마",
        },
        {
            "id" : 10,
            "name" : "고구마",
        },
    ]

2021-06-14 06:10 UTC, lordmyshepherd requested changes

2021-06-14 06:10 UTC, lordmyshepherd commented on ingredient/views.py
> +class ShowRecipeInfo(View):
일단 recipe와 ingradient를 분리하신 것 👍 👍
위에 피드백 드린 내용과 동일하게 수정하시면 좋을 것 같습니다!

2021-06-14 06:10 UTC, lordmyshepherd commented on ingredient/views.py
> +            print(e)
로그를 찍고 싶으셨다고 하면 python 내장 모듈인 `logging`을 활용하시면 좋을 것 같습니다!
다만 위 케이스에서는 에러가 raise될 수 있는 상황이 `get()`를 호출 했을 경우 밖에 없을 것 같습니다.
`Recipe.DoseNotExist`에러를 찾아서 적용해주시면 좋을 것 같네요!

```python
import logging
```

2021-06-14 06:17 UTC, lordmyshepherd commented
**질문하신 내용**
- 현재 깃이 충돌할까봐 ingredient,recipe의 subpage를 ingredient 폴더에서 작업하고 있고 ingredient,recipe의 mainpage를 recipe페이지에서 작업을 하고 있습니다. 조금 기형적으로 구성이 되고 있는 것 같습니다.
> 충돌에 맞서 싸우세요!!! 🔥🔥🔥 

- 폴더를 다시 구성을 해서 기능적으로 (mainpage, subpage폴더로 구성을 할지 ) 구분을 할지 
> `recipe`와 `ingredient` app을 나누시는게 좋을 것 같습니다. (RESTful하게 만들기 편합니다.)

- 기존 방식으로 (ingredient, recipe 폴더에)하되 각각 폴더에 메인페이지 조회와 상세페이지 조회를 합쳐넣을지(ingredient 폴더 안에 ingredient mainpage, subpage 조회 로직 같이 위치)  고민입니다.
> app을 분리하면 해결될 것 같네요!

- ingredient url = ingredient/detail  //  recipe url = recipe/detail로 구성했는데 restful한지 궁금합니다.
> 리뷰에 남겨드렸습니다. 확인부탁드려요~

- 에러처리를 exception으로 통합한다음에 print(e)로 에러메시지를 확인하는 방식으로 진행했는데 에러를 세분화하는 것이 좋은지 아니면 백엔드에서만 에러의 원인을 파악하는 것이 좋은 지 궁금합니다. 
> 리뷰 남겨드렸습니다.
> 에러는 debug 해야 되는 상황을 생각해보면서 핸들링해주시면 좋을 것 같아요~ front에서 error를 직접 마주하게 되면 보안적 문제가 있을 수 있습니다. 그렇기 때문에 발생하는 error에 대해서 `Exception as e`와 같이 빼서 백엔드가 모니터링할 수 있는 서버에서만 에러를 보는 방향이 좋습니다. 다만 print가 아니라 logging 모듈을 사용해주세요~

2021-06-14 07:33 UTC, kevin-hyun commented on ingredient/urls.py
> +    path('/detail',ShowIngredientInfo.as_view()),
페이지적으로 생각을 했는데 상세정보를 불러올때 이 API를 여러곳에서 사용한다고 생각을 하면 다르게 구성을 해야겠습니다!

2021-06-14 07:33 UTC, kevin-hyun commented on ingredient/views.py
> +from django.views      import View
저렇게 제가 타이핑 하지 않은 import가 들어가는 것은 어떻게 막는 방법 있을까요?

2021-06-14 07:35 UTC, kevin-hyun commented on ingredient/views.py
> +class ShowIngredientInfo(View):
똑같이 Ingredient로 하면 ingredient.models에서 import 한 Ingredient와 혼동이 일어나지는 않을까요>?? 알아서 참조가 잘될까요??

2021-06-14 08:34 UTC, kevin-hyun commented on ingredient/views.py
> +            request_id  = request.GET.get('id',None)
구현완료!!

2021-06-14 08:34 UTC, kevin-hyun commented on ingredient/views.py
> +            print(e)
logging은 생각보다 적용하기 어려워서 추후에 여유생기면 넣어보겠습니다!

2021-06-14 08:41 UTC, kevin-hyun commented on ingredient/views.py
> +            }
수정완료했습니다 !

2021-06-14 09:17 UTC, lordmyshepherd commented on ingredient/views.py
> +class ShowIngredientInfo(View):
`IngredientView`로 수정해주세요~ django convention이에요! View class에 상속받은 class를 붙여준답니다!

2021-06-14 09:17 UTC, lordmyshepherd commented on ingredient/views.py
> +            print(e)
👍

2021-06-14 14:21 UTC, lordmyshepherd requested changes

2021-06-14 14:21 UTC, lordmyshepherd commented on ingredient/urls.py
> +from ingredient.views import IngredientView
```suggestion
from django.urls          import path
from ingredient.views import IngredientView
```

2021-06-14 14:21 UTC, lordmyshepherd commented on ingredient/urls.py
> +    path('/<int:ingredient_id>',IngredientView.as_view()),
```suggestion
    path('/<int:ingredient_id>', IngredientView.as_view()),
```

2021-06-14 14:21 UTC, lordmyshepherd commented on ingredient/views.py
> +    def get (self,request,ingredient_id):
```suggestion
    def get (self, request, ingredient_id): 
```

2021-06-14 14:21 UTC, lordmyshepherd commented on ingredient/views.py
> +            }
아래와 같이 코드를 줄여볼 수 있지 않을까요?

```suggestion
            ingredient  = Ingredient.objects.get(id = ingredient_id)
            result = {
                "id"               : ingredient.id,
                "name"             : ingredient.name,
                "price"            : ingredient.price,
                "info"             : ingredient.info,
                "storage"          : ingredient.storage,
                "image_url"        : ingredient.image_url,
                "related_recipe"   : [{
                    "id"        : recipe.id,
                    "name"      : recipe.name,
                    "image_url" : recipe.image_url
                } for recipe in ingredient.recipe_set.all()] 
            }
```

2021-06-14 14:21 UTC, lordmyshepherd commented on ingredient/views.py
> +            return JsonResponse({"ingredient":info_dict})
```suggestion
            return JsonResponse({"ingredient": result})
```

2021-06-14 14:21 UTC, lordmyshepherd commented on recipe/views.py
> +class RecipeView(View):
여기도 위에서 피드백 드린 내용 반영해주시면 좋을 것 같아요~

2021-06-14 14:21 UTC, lordmyshepherd commented on user/utils.py
> +def login_decorator(func):
해당 코드는 다른 PR에서 본 코드 같은데, 왜 여기에 또 있는건가요??

2021-06-15 01:26 UTC, kevin-hyun commented on ingredient/views.py
> +            return JsonResponse({"ingredient":info_dict})
아하! 결과는 result로 표현하는게 좋군요!

2021-06-15 01:27 UTC, kevin-hyun commented on ingredient/views.py
> +    def get (self,request,ingredient_id):
, 사이 띄어주기!

2021-06-15 01:27 UTC, kevin-hyun commented on ingredient/urls.py
> +    path('/<int:ingredient_id>',IngredientView.as_view()),
, 사이 띄어주기!

2021-06-15 01:27 UTC, kevin-hyun commented on ingredient/urls.py
> +from ingredient.views import IngredientView
컨벤션 지키기 !!

2021-06-15 08:25 UTC, kevin-hyun commented on ingredient/views.py
> +            }
적용완료했습니다!  신세계~~

2021-06-15 08:25 UTC, kevin-hyun commented on user/utils.py
> +def login_decorator(func):
삭제완료!

2021-06-15 08:25 UTC, kevin-hyun commented on recipe/views.py
> +class RecipeView(View):
적용 완료!

2021-06-16 01:26 UTC, lordmyshepherd requested changes

2021-06-16 01:26 UTC, lordmyshepherd commented on ingredient/views.py
> +            }
한줄이라도 더 줄여보면 어떨까요? 그리고 `related_recipe` 보다는 `related_recipes`가 좋을 것 같습니다! 

```suggestion
            ingredient  = Ingredient.objects.get(id=ingredient_id)
            result      = {
                "id"               : ingredient.id,
                "name"             : ingredient.name,
                "price"            : ingredient.price,
                "info"             : ingredient.info,
                "storage"          : ingredient.storage,
                "image_url"        : ingredient.image_url,
                "related_recipes"  : [{
                    "id"        : recipe.id,
                    "name"      : recipe.name,
                    "image_url" : recipe.image_url
                } for recipe in ingredient.recipe.all()]
            }
```

2021-06-16 01:26 UTC, lordmyshepherd commented on recipe/views.py
> +        try:
여기도 위에서 드린 피드백 내용 적용해보면 어떨까요?

2021-06-16 01:26 UTC, lordmyshepherd commented on ingredient/views.py
> +        except ObjectDoesNotExist:
아래와 같이 어떤 객체가 존재하지 않는지 좀더 명확하게 에러를 잡아줄 수 있을 것 같습니다.
`ObjectDoesNotXist` class를 한번 더 감싼 `Ingredient.DoesNotExist`를 사용하면 디버깅하기도 더 쉽고 코드 가독성도 좋아집니다!

![image](https://user-images.githubusercontent.com/53214510/122143815-2c11b280-ce8d-11eb-8738-1c3fa19108eb.png)


```suggestion
        except Ingredient.DoesNotExist:
```

2021-06-16 04:46 UTC, kevin-hyun commented on ingredient/views.py
> +        except ObjectDoesNotExist:
장고에서 더 지원해주는 기능이었군요!! 이해안갔었는데 짚어주셔서 이해됐어요!

2021-06-16 04:46 UTC, kevin-hyun commented on recipe/views.py
> +        try:
적용 완료입니다~

2021-06-16 04:47 UTC, kevin-hyun commented on ingredient/views.py
> +            }
이렇게도 코드 줄일 수 있군요! 감사합니다~

2021-06-16 07:05 UTC, lordmyshepherd requested changes

2021-06-16 07:05 UTC, lordmyshepherd commented on ingredient/views.py
> +            }
```suggestion
                "related_recipes"  : [{
                     "id"        : recipe.id,
                     "name"      : recipe.name,
                     "image_url" : recipe.image_url
                 } for recipe in ingredient.recipe.all()]
            }
```

2021-06-16 07:13 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-06-16 07:14 UTC, merged