Feature/carts
wecode-bootcamp-korea/21-1st-Ojusmarket-backend pull request #12
Opened 2021-06-15 09:17 UTC by ttakku-park

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장바구니 추가기능, 장바구니 조회기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 장바구니 추가기능 (post) : 1. 최소수량이 0 이하일 경우 에러처리 2. 같은 상품 장바구니 추가 시 db에 생성하지않고 기존 상품의 count (수량) 추가 3. 장바구니 추가시 db에 생성  4. Cart 테이블에 없는 유저 필터 시 예외처리
- 장바구니 조회기능 (get) : user id 값을 별도로 받지않고 user token 정보로 특정유저의 장바구니 조회 (프론트에서 딕셔너리를 list 형태로 감싸서 제공 요구 ), Cart 테이블에 없는 유저 필터 시 예외처리

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 특이사항 : 장바구니 삭제 기능은 구현 전 입니다 ! 장바구니 상품선택기능은 프론트분들과 협의중에 있습니다 
- 질문사항 : post 의 중복제품 count up 부분에서 save 메소드를 사용하였는데 통신시 서버창에 save 메소드로 인해 반환되는 특정값이 뜹니다이렇게 둬도 괜찮은 부분일까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-15 09:24 UTC, ttakku-park commented
조회 기능 스크린샷
![스크린샷 2021-06-15 오후 6 20 09](https://user-images.githubusercontent.com/78678551/122027906-7734b280-ce06-11eb-8755-db6ab021362d.png)

생성 기능 스크린샷
![스크린샷 2021-06-15 오후 6 20 40](https://user-images.githubusercontent.com/78678551/122028017-90d5fa00-ce06-11eb-977f-da0d61603313.png)

db carts 테이블 스크린샷 (중복 제품 확인차 계속 생성된 값입니다! 마지막 row는 로직 구현 성공 후 같은 제품을 추가해 count가 추가 된 것입니다.) 
<img width="312" alt="스크린샷 2021-06-15 오후 6 21 00" src="https://user-images.githubusercontent.com/78678551/122028279-d7c3ef80-ce06-11eb-9352-fb50c6eebe1d.png">

2021-06-16 02:13 UTC, lordmyshepherd requested changes

2021-06-16 02:13 UTC, lordmyshepherd commented on cart/views.py
> +            duplicate_user = Cart.objects.filter(user_id=user.id)
`.objects` manage class의 `filter()` method를 호출하면, 반환되는 객체는 
`QuerySet`(일종의 리스트라고 생각하시면 됩니다.)에 `Cart Instance`(테이블의 한 row 또는 record라고도 합니다.)가 담겨 있는 형태입니다.

그렇기 때문에 변수에 할당할 때, 보다 명확한 변수명을 사용해주셔야 합니다.

`<QuerySet : [ <Cart 1>, <Cart2> ...]`

```suggestion
            carts = Cart.objects.filter(user_id=user.id)
```

2021-06-16 02:13 UTC, lordmyshepherd commented on cart/views.py
> +                )
처음에 input으로 받은 `ingredient_id`와 `user_id`로 같이 조회하면 `반복문`을 사용할 필요가 없을 것 같습니다.
아래 코드를 참고해서 수정해보시면 좋을 것 같습니다!

```python
cart = Cart.objects.get(user_id = user.id, ingredient_id = ingredient_id)                    
```

2021-06-16 02:13 UTC, lordmyshepherd commented on cart/views.py
> +
위에서 드린 피드백과 같습니다.
추가로, `user = request.user`의 경우 아래에서 계속 사용되는게 아니라고 하면, 굳이 변수로 만들 필요가 없어 보입니다.
아래와 같이 필요한 곳에서 바로 사용하면 좋을 것 같습니다!

```suggestion
            carts = Cart.objects.filter(user_id=request.user)
            
            for cart in carts :
                ...
```

2021-06-16 05:12 UTC, ttakku-park commented on cart/views.py
> +            duplicate_user = Cart.objects.filter(user_id=user.id)
수정하겠습니다!

2021-06-16 09:00 UTC, ttakku-park commented on cart/views.py
> +                )
수정 완료하였습니다!

2021-06-16 09:02 UTC, ttakku-park commented on cart/views.py
> +
post부분은 는 3개 이상이라  변수에 저장하였고 get 부분에서는 한번밖에 사용이 안되어 바로 사용할 수 있도록 수정하였습니다!

2021-06-17 01:55 UTC, lordmyshepherd requested changes

2021-06-17 01:55 UTC, lordmyshepherd commented on cart/views.py
> +                )
`get_or_create()` method를 사용하면 코드 수를 많이 줄일 수 있겠네요!
한번 검색해서 공부해보시고 적용해보시면 좋을 것 같아요! 만약 다른 기능도 구현해야되는게 남았다고 하면 2차에 사용해보세요~

```suggestion
    try:
            data          = data = json.loads(request.body)
            cart, created = get_or_create(user_id = request.user_id, ingredient_id = data['ingredient_id']) 
            cart.count += data["count"]                
            cart.save()                
            
            return JsonResponse({'message':'SUCCESS'}, status=200) 
            
    except:
            ..
```

2021-06-17 01:55 UTC, lordmyshepherd commented on cart/views.py
> +                cart_list.append(cart_info)
변수가 verbose하지 않고 좀 더 간단하게 선언하면 가독성이 좋아질 것 같아요!
`Cart.objects.filter(user=request.user)`가 호출되고 반환되는 객체는 cart 인스턴스 입니다.

아래 코드도 한줄 더 줄여볼 수 있겠네요. cart info를 아래 여러곳에서 사용하는게 아니라면 바로 배열에 append하는게 더 좋을 것 같습니다.
```suggestion
            carts = Cart.objects.filter(user=request.user)
            
            cart_list = []

            for cart in carts:
                cart_list.append({
                    'id'       : cart.ingredient.id,
                    'name'     : cart.ingredient.name,
                    'price'    : cart.ingredient.price,
                    'image_url': cart.ingredient.image_url,
                    'count'    : cart.count
                })
```

2021-06-17 01:55 UTC, lordmyshepherd commented on cart/views.py
> +            return JsonResponse({"message": "SUCCESSFUL_DELETION"}, status=200)
이경우에 지우고자하는 cart_id나 ingredient_id 리스트만 받아오면 됩니다.
`input : [1, 2, 3]`
 
```suggestion
            user = request.user
            
            carts = Cart.objects.filter(user_id=user.id, ingredient_id__in = data["ingredient_ids"]
            carts.delete()
            
            return JsonResponse({"message": "NO_CONTENT"}, status=204)
```

2021-06-17 03:43 UTC, ttakku-park commented on cart/views.py
> +                )
확인했습니다! 적용해보겠습니다!

2021-06-17 03:50 UTC, ttakku-park commented on cart/views.py
> +                cart_list.append(cart_info)
변수명 지을 때 반환되는 객체를 생각하면 되겠네여! 물론 그게 어렵지만 ㅎㅎ.. append는 좀 더 고민하고 작성했으면 피드백 주신 대로 작성할 수 있었을텐데 ㅠㅠ 앞으로 한번 더 생각하고 작성하겠습니다 ㅠㅠ!

2021-06-17 06:18 UTC, ttakku-park commented on cart/views.py
> +                )
이번프로젝트 끝나고 추가로 공부하도록 하겠습니다. 감사합니다!!

2021-06-17 06:20 UTC, ttakku-park commented on cart/views.py
> +            return JsonResponse({"message": "SUCCESSFUL_DELETION"}, status=200)
수정완료했습니다.

2021-06-17 07:44 UTC, lordmyshepherd commented on cart/views.py
> +
위 코드에서 KeyError가 발생할 케이스가 없는 것 같아요!

2021-06-17 07:44 UTC, lordmyshepherd commented on cart/views.py
> +
언제 KeyError가 발생하나요?

2021-06-17 07:57 UTC, lordmyshepherd requested changes

2021-06-17 07:57 UTC, lordmyshepherd commented on cart/views.py
> +            [data_list.append(cart['id']) for cart in data]
```suggestion
            data_list = [cart['id'] for cart in data]
```

2021-06-17 07:57 UTC, lordmyshepherd commented on cart/views.py
> +            [data_list.append(cart['id']) for cart in data]
```suggestion
            cart_ids = data["cart_ids"]
            # [1, 2, 3]
```

2021-06-17 07:57 UTC, lordmyshepherd commented on cart/views.py
> +            return JsonResponse({'message': 'THIS_ACCOUNT_DOES_NOT_EXIST'}, status=400)
해당 에러가 raise될 수 있는 상황이 있을까요?

2021-06-17 07:57 UTC, lordmyshepherd commented on cart/views.py
> +            for data_i in data:
다음에는 `builk_update()` method를 사용해보세요~
https://docs.djangoproject.com/en/3.2/ref/models/querysets/

2021-06-17 08:39 UTC, ttakku-park commented on cart/views.py
> +            [data_list.append(cart['id']) for cart in data]
프론트랑 합의하여 list 형태로 받기로 하였습니다!! 이에 따른 로직 수정하였습니다!

2021-06-17 09:53 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-06-17 10:09 UTC, merged